#!/usr/bin/env ruby

# A few helpful tips about the Rules file:
#
# * The string given to #compile and #route are matching patterns for
#   identifiers--not for paths. Therefore, you can't match on extension.
#
# * The order of rules is important: for each item, only the first matching
#   rule is applied.
#
# * Item identifiers start and end with a slash (e.g. "/about/" for the file
#   "content/about.html"). To select all children, grandchildren, ... of an
#   item, use the pattern "/about/*/"; "/about/*" will also select the parent,
#   because "*" matches zero or more characters.

compile '/style/*/' do
  # don't filter or layout
end
compile '/script/*/' do
  # don't filter or layout
end
compile '/dimagispace/*' do
  # don't filter or layout
end

compile '/*/script/*/' do
  # don't filter or layout
end

compile '/pubkey/' do
  filter :erb
end

compile '/travel/blog/labrador/*/' do
  filter :erb
  layout 'labrador'
end

compile '*' do
  if item.binary?
    # don't filter binary items
  else
    filter :erb
    layout 'default'
  end
end

route '/style/*/' do
  item.identifier.chop + '.css'
end
route '/script/*/' do
  item.identifier.chop + '.' + item[:extension]
end
route '/dimagispace/*/' do
  item.identifier.chop + '.' + item[:extension]
end

route '/*/script/*/' do
  item.identifier.chop + '.' + item[:extension]
end

route '/pubkey/' do
  item.identifier.chop + '.txt'
end

route '/projects/' do
  '/index.html'
end
route '*' do
  if item.binary?
    # Write item with identifier /foo/ to /foo.ext
    item.identifier.chop + '.' + item[:extension]
  else
    # Write item with identifier /foo/ to /foo/index.html
    item.identifier + 'index.html'
  end
end

layout '*', :erb
